# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=50)),
                ('temperature', models.FloatField(default=0.0)),
            ],
        ),
    ]
